/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'customerName' : string,
  'status' : AppointmentStatus,
  'customerNumber' : string,
  'date' : string,
  'createdAt' : bigint,
  'time' : string,
  'updatedAt' : bigint,
  'notes' : string,
  'customerId' : Principal,
}
export type AppointmentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface TimeSlot {
  'id' : bigint,
  'date' : string,
  'time' : string,
  'isBooked' : boolean,
}
export interface UserProfile {
  'customerNumber' : [] | [string],
  'name' : string,
  'role' : { 'pa' : null } |
    { 'admin' : null } |
    { 'customer' : null },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptAppointment' : ActorMethod<[bigint], undefined>,
  'addTimeSlot' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookTimeSlot' : ActorMethod<[bigint], undefined>,
  'completeAppointment' : ActorMethod<[bigint], undefined>,
  'createAppointment' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createUser' : ActorMethod<
    [
      Principal,
      string,
      { 'pa' : null } |
        { 'admin' : null } |
        { 'customer' : null },
    ],
    string
  >,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllTimeSlots' : ActorMethod<[], Array<TimeSlot>>,
  'getAppointment' : ActorMethod<[bigint], Appointment>,
  'getAppointmentStats' : ActorMethod<
    [],
    {
      'pending' : bigint,
      'completed' : bigint,
      'rejected' : bigint,
      'accepted' : bigint,
    }
  >,
  'getAvailableTimeSlots' : ActorMethod<[], Array<TimeSlot>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'rejectAppointment' : ActorMethod<[bigint], undefined>,
  'removeTimeSlot' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUser' : ActorMethod<
    [
      Principal,
      string,
      { 'pa' : null } |
        { 'admin' : null } |
        { 'customer' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];