/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : AppointmentStatus,
  'customerNumber' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'customerId' : IDL.Principal,
});
export const TimeSlot = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'isBooked' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'customerNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Variant({
    'pa' : IDL.Null,
    'admin' : IDL.Null,
    'customer' : IDL.Null,
  }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptAppointment' : IDL.Func([IDL.Nat], [], []),
  'addTimeSlot' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookTimeSlot' : IDL.Func([IDL.Nat], [], []),
  'completeAppointment' : IDL.Func([IDL.Nat], [], []),
  'createAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createUser' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Variant({
          'pa' : IDL.Null,
          'admin' : IDL.Null,
          'customer' : IDL.Null,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'getAppointmentStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'pending' : IDL.Nat,
          'completed' : IDL.Nat,
          'rejected' : IDL.Nat,
          'accepted' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAvailableTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'rejectAppointment' : IDL.Func([IDL.Nat], [], []),
  'removeTimeSlot' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUser' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Variant({
          'pa' : IDL.Null,
          'admin' : IDL.Null,
          'customer' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : AppointmentStatus,
    'customerNumber' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'customerId' : IDL.Principal,
  });
  const TimeSlot = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'isBooked' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'customerNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Variant({
      'pa' : IDL.Null,
      'admin' : IDL.Null,
      'customer' : IDL.Null,
    }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptAppointment' : IDL.Func([IDL.Nat], [], []),
    'addTimeSlot' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookTimeSlot' : IDL.Func([IDL.Nat], [], []),
    'completeAppointment' : IDL.Func([IDL.Nat], [], []),
    'createAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createUser' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Variant({
            'pa' : IDL.Null,
            'admin' : IDL.Null,
            'customer' : IDL.Null,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
    'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'getAppointmentStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'pending' : IDL.Nat,
            'completed' : IDL.Nat,
            'rejected' : IDL.Nat,
            'accepted' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAvailableTimeSlots' : IDL.Func([], [IDL.Vec(TimeSlot)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'rejectAppointment' : IDL.Func([IDL.Nat], [], []),
    'removeTimeSlot' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUser' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Variant({
            'pa' : IDL.Null,
            'admin' : IDL.Null,
            'customer' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };