/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimeSlot {
    id: bigint;
    date: string;
    time: string;
    isBooked: boolean;
}
export interface Appointment {
    id: bigint;
    customerName: string;
    status: AppointmentStatus;
    customerNumber: string;
    date: string;
    createdAt: bigint;
    time: string;
    updatedAt: bigint;
    notes: string;
    customerId: Principal;
}
export interface UserProfile {
    customerNumber?: string;
    name: string;
    role: Variant_pa_admin_customer;
}
export enum AppointmentStatus {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pa_admin_customer {
    pa = "pa",
    admin = "admin",
    customer = "customer"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptAppointment(appointmentId: bigint): Promise<void>;
    addTimeSlot(date: string, time: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookTimeSlot(slotId: bigint): Promise<void>;
    bootstrapAdmin(name: string): Promise<void>;
    completeAppointment(appointmentId: bigint): Promise<void>;
    createAppointment(customerName: string, customerNumber: string, date: string, time: string, notes: string): Promise<bigint>;
    createUser(user: Principal, name: string, role: Variant_pa_admin_customer): Promise<string>;
    deleteUser(user: Principal): Promise<void>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllTimeSlots(): Promise<Array<TimeSlot>>;
    getAppointment(id: bigint): Promise<Appointment>;
    getAppointmentStats(): Promise<{
        pending: bigint;
        completed: bigint;
        rejected: bigint;
        accepted: bigint;
    }>;
    getAvailableTimeSlots(): Promise<Array<TimeSlot>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyAppointments(): Promise<Array<Appointment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdminBootstrapped(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listUsers(): Promise<Array<[Principal, UserProfile]>>;
    rejectAppointment(appointmentId: bigint): Promise<void>;
    removeTimeSlot(slotId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateUser(user: Principal, name: string, role: Variant_pa_admin_customer): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptAppointment(arg0);
            return result;
        }
    }
    async addTimeSlot(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTimeSlot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTimeSlot(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookTimeSlot(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookTimeSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookTimeSlot(arg0);
            return result;
        }
    }
    async completeAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeAppointment(arg0);
            return result;
        }
    }
    async createAppointment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createUser(arg0: Principal, arg1: string, arg2: Variant_pa_admin_customer): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTimeSlots(): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimeSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimeSlots();
            return result;
        }
    }
    async getAppointment(arg0: bigint): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_Appointment_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_Appointment_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentStats(): Promise<{
        pending: bigint;
        completed: bigint;
        rejected: bigint;
        accepted: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentStats();
            return result;
        }
    }
    async getAvailableTimeSlots(): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointments();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointments();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async bootstrapAdmin(arg0: string): Promise<void> {
        const result = await (this.actor as any).bootstrapAdmin(arg0);
        return result;
    }
    async isAdminBootstrapped(): Promise<boolean> {
        const result = await (this.actor as any).isAdminBootstrapped();
        return result;
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectAppointment(arg0);
            return result;
        }
    }
    async removeTimeSlot(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTimeSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTimeSlot(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUser(arg0: Principal, arg1: string, arg2: Variant_pa_admin_customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerNumber: [] | [string];
    name: string;
    role: {
        pa: null;
    } | {
        admin: null;
    } | {
        customer: null;
    };
}): {
    customerNumber?: string;
    name: string;
    role: Variant_pa_admin_customer;
} {
    return {
        customerNumber: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.customerNumber)),
        name: value.name,
        role: from_candid_variant_n13(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _AppointmentStatus;
    customerNumber: string;
    date: string;
    createdAt: bigint;
    time: string;
    updatedAt: bigint;
    notes: string;
    customerId: Principal;
}): {
    id: bigint;
    customerName: string;
    status: AppointmentStatus;
    customerNumber: string;
    date: string;
    createdAt: bigint;
    time: string;
    updatedAt: bigint;
    notes: string;
    customerId: Principal;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_AppointmentStatus_n7(_uploadFile, _downloadFile, value.status),
        customerNumber: value.customerNumber,
        date: value.date,
        createdAt: value.createdAt,
        time: value.time,
        updatedAt: value.updatedAt,
        notes: value.notes,
        customerId: value.customerId
    };
}
function from_candid_tuple_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pa: null;
} | {
    admin: null;
} | {
    customer: null;
}): Variant_pa_admin_customer {
    return "pa" in value ? Variant_pa_admin_customer.pa : "admin" in value ? Variant_pa_admin_customer.admin : "customer" in value ? Variant_pa_admin_customer.customer : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): AppointmentStatus {
    return "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "rejected" in value ? AppointmentStatus.rejected : "accepted" in value ? AppointmentStatus.accepted : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n5(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerNumber?: string;
    name: string;
    role: Variant_pa_admin_customer;
}): {
    customerNumber: [] | [string];
    name: string;
    role: {
        pa: null;
    } | {
        admin: null;
    } | {
        customer: null;
    };
} {
    return {
        customerNumber: value.customerNumber ? candid_some(value.customerNumber) : candid_none(),
        name: value.name,
        role: to_candid_variant_n3(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pa_admin_customer): {
    pa: null;
} | {
    admin: null;
} | {
    customer: null;
} {
    return value == Variant_pa_admin_customer.pa ? {
        pa: null
    } : value == Variant_pa_admin_customer.admin ? {
        admin: null
    } : value == Variant_pa_admin_customer.customer ? {
        customer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
